import { useCallback } from 'react'
import JSZip from 'jszip'
import { captureScreenAtFullRes } from '../utils/screenCapture'
import { convertTreeToTSX } from '../utils/exportTsx'
import { getDevicePreset } from '../constants/devices'
import {
  generateAppTsx, generateAppJson, generatePackageJson,
  generateTsConfig, generateBabelConfig, generateGitignore,
  generateReadme as generateExpoReadme,
  generateMultiScreenAppTsx, generateMultiScreenPackageJson,
  generateMultiScreenAppJson, generateMultiScreenReadme,
} from '../utils/expoScaffold'
import { detectTabGroup } from '../utils/detectTabBar'
import { trackEvent } from '../lib/analytics'
import type { ComponentNode } from '../types/mokkoi'

export interface ExportTarget {
  screenId: string
  screenName: string
  tree: ComponentNode
  deviceId: string
  originalPrompt?: string
}

interface UseScreenExportOpts {
  phoneFrameRefs: React.RefObject<Map<string, HTMLDivElement>>
  onToast: (msg: string) => void
}

/** Filler prefixes to strip from prompt-style names */
const FILLER_RE = /^(create|make|design|build|generate|regenerate)\s+(a|an|the|my|this)\s+/i

/** Noise words to drop from component names */
const NOISE_WORDS = new Set([
  'a', 'an', 'the', 'my', 'this', 'that', 'for', 'with', 'and', 'or', 'of', 'in', 'on', 'to',
  'style', 'styled', 'like', 'screen', 'page', 'app', 'version', 'v1', 'v2', 'v3',
])

/**
 * PascalCase name for TSX component filenames.
 * Strips prompt filler ("Create a", "Design a"), noise words, and keeps meaningful tokens.
 * "Create a fitness dashboard with progress rings" → "FitnessDashboardProgressRings"
 * "DELIVER TO HOME" → "DeliverToHome"
 * "Create a food delivery app v1" → "FoodDelivery"
 */
function safeName(name: string): string {
  let cleaned = (name || 'Screen')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()

  // Strip prompt-style filler prefix
  cleaned = cleaned.replace(FILLER_RE, '')

  const allWords = cleaned.split(/\s+/).filter(w => w.length > 0)
  // Drop noise words, but fall back to all words if nothing survives
  const words = allWords.filter(w => !NOISE_WORDS.has(w.toLowerCase()))
  const final = words.length > 0 ? words : allWords

  if (final.length === 0) return 'Screen'

  const pascal = final
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')

  // Cap at 40 chars but don't cut mid-word
  if (pascal.length <= 40) return pascal
  let cut = pascal.slice(0, 40)
  const lastUpper = cut.lastIndexOf(cut.match(/[A-Z][^A-Z]*$/)?.[0] || '')
  if (lastUpper > 10) cut = cut.slice(0, lastUpper)
  return cut || pascal.slice(0, 40)
}

/** Clean filename: remove special chars, replace spaces with underscores, prefix with Mokkoi_ */
function brandedName(name: string): string {
  const clean = (name || 'Screen')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 40)
  return `Mokkoi_${clean}`
}

function generateReadme(target: ExportTarget): string {
  const device = getDevicePreset(target.deviceId)
  const name = safeName(target.screenName)
  return `# ${target.screenName}

Generated by [Mokkoi](https://mokkoi.com)

## Screen Info

- **Name:** ${target.screenName}
- **Device:** ${device.name} (${device.width}x${device.height})
${target.originalPrompt ? `- **Prompt:** ${target.originalPrompt}` : ''}

## Quick Start with Expo

\`\`\`bash
npx create-expo-app my-app --template blank-typescript
cd my-app
\`\`\`

Copy \`${name}.tsx\` into your project, then import it:

\`\`\`tsx
import ${name}Screen from './${name}';

export default function App() {
  return <${name}Screen />;
}
\`\`\`

Run:

\`\`\`bash
npx expo start
\`\`\`

## Files

| File | Description |
|------|-------------|
| \`screen.png\` | High-resolution screenshot (@2x) |
| \`${name}.tsx\` | React Native component |
| \`README.md\` | This file |
`
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function useScreenExport({ phoneFrameRefs, onToast }: UseScreenExportOpts) {
  const downloadPNG = useCallback(async (target: ExportTarget) => {
    onToast('Capturing screenshot...')
    try {
      const blob = await captureScreenAtFullRes(target.screenId, phoneFrameRefs.current!)
      triggerDownload(blob, `${brandedName(target.screenName)}.png`)
      onToast('Screenshot saved!')
      trackEvent('screen_downloaded', { format: 'png' })
    } catch (err) {
      onToast(`Screenshot failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [phoneFrameRefs, onToast])

  const downloadTSX = useCallback((target: ExportTarget) => {
    try {
      const code = convertTreeToTSX(target.tree, target.screenName)
      const blob = new Blob([code], { type: 'text/plain' })
      triggerDownload(blob, `${brandedName(target.screenName)}.tsx`)
      onToast('Code downloaded!')
      trackEvent('screen_downloaded', { format: 'tsx' })
    } catch (err) {
      onToast(`Download failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [onToast])

  const downloadZIP = useCallback(async (target: ExportTarget) => {
    onToast('Preparing package...')
    try {
      const zip = new JSZip()
      const name = safeName(target.screenName)

      // Screenshot
      const pngBlob = await captureScreenAtFullRes(target.screenId, phoneFrameRefs.current!)
      zip.file('screen.png', pngBlob)

      // Code
      zip.file(`${name}.tsx`, convertTreeToTSX(target.tree, target.screenName))

      // README
      zip.file('README.md', generateReadme(target))

      const zipBlob = await zip.generateAsync({ type: 'blob' })
      triggerDownload(zipBlob, `${brandedName(target.screenName)}.zip`)
      onToast('Package downloaded!')
      trackEvent('screen_downloaded', { format: 'zip' })
    } catch (err) {
      onToast(`Package failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [phoneFrameRefs, onToast])

  const downloadExpoProject = useCallback(async (target: ExportTarget, projectName: string) => {
    onToast('Building Expo project...')
    try {
      const zip = new JSZip()
      const name = safeName(target.screenName)
      const device = getDevicePreset(target.deviceId)
      const opts = {
        screenName: name,
        projectName,
        prompt: target.originalPrompt,
        deviceWidth: device.width,
        deviceHeight: device.height,
      }

      zip.file('App.tsx', generateAppTsx(opts))
      zip.file(`${name}.tsx`, convertTreeToTSX(target.tree, target.screenName))
      zip.file('app.json', generateAppJson(opts))
      zip.file('package.json', generatePackageJson(opts))
      zip.file('tsconfig.json', generateTsConfig())
      zip.file('babel.config.js', generateBabelConfig())
      zip.file('.gitignore', generateGitignore())
      zip.file('README.md', generateExpoReadme(opts))

      const zipBlob = await zip.generateAsync({ type: 'blob' })
      triggerDownload(zipBlob, `${brandedName(target.screenName)}_Expo.zip`)
      onToast('Expo project downloaded!')
      trackEvent('screen_downloaded', { format: 'expo' })
    } catch (err) {
      onToast(`Export failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [onToast])

  /** Export entire project as multi-screen Expo app with React Navigation */
  const downloadExpoMultiScreen = useCallback(async (
    allScreens: ExportTarget[],
    projectName: string,
    connections?: { fromScreenId: string; toScreenId: string }[],
  ) => {
    if (allScreens.length === 0) {
      onToast('No screens to export')
      return
    }

    // Single screen → use the simpler single-screen export
    if (allScreens.length === 1) {
      return downloadExpoProject(allScreens[0], projectName)
    }

    onToast(`Building Expo project (${allScreens.length} screens)...`)
    try {
      const zip = new JSZip()

      // Build screen name list (deduplicate PascalCase names)
      const usedNames = new Set<string>()
      const screenMeta: { name: string; prompt?: string }[] = []
      const nameToTree: { name: string; tree: ComponentNode }[] = []

      // First pass: assign PascalCase names
      const screenIdToName = new Map<string, string>()
      for (const screen of allScreens) {
        let name = safeName(screen.screenName)
        if (usedNames.has(name)) {
          let i = 2
          while (usedNames.has(`${name}${i}`)) i++
          name = `${name}${i}`
        }
        usedNames.add(name)
        screenIdToName.set(screen.screenId, name)
        screenMeta.push({ name, prompt: screen.originalPrompt })
        nameToTree.push({ name, tree: screen.tree })
      }

      // Build per-screen navigation targets from connections
      // Key: source screen ID → Map of target screen name (used in navigate())
      const screenNavTargets = new Map<string, Map<string, string>>()
      if (connections && connections.length > 0) {
        for (const conn of connections) {
          const targetName = screenIdToName.get(conn.toScreenId)
          if (!targetName) continue
          if (!screenNavTargets.has(conn.fromScreenId)) {
            screenNavTargets.set(conn.fromScreenId, new Map())
          }
          // Use the target screen's display name as a fuzzy match trigger
          const targetScreen = allScreens.find(s => s.screenId === conn.toScreenId)
          if (targetScreen) {
            // Match buttons containing the target screen name words
            const words = targetScreen.screenName.toLowerCase().split(/\s+/).filter(w => w.length > 3)
            for (const word of words) {
              screenNavTargets.get(conn.fromScreenId)!.set(word, targetName)
            }
          }
        }
      }

      // Second pass: generate TSX with navigation targets
      for (const screen of allScreens) {
        const name = screenIdToName.get(screen.screenId)!
        const navTargets = screenNavTargets.get(screen.screenId)
        const tsx = convertTreeToTSX(screen.tree, screen.screenName, { navigationTargets: navTargets })
        zip.file(`screens/${name}.tsx`, tsx)
      }

      // Detect tab bar group (screens sharing the same bottom tab bar)
      const tabGroup = detectTabGroup(nameToTree)

      const multiOpts = { projectName, screens: screenMeta, tabGroup }

      // App.tsx with NavigationContainer + Stack
      zip.file('App.tsx', generateMultiScreenAppTsx(multiOpts))
      zip.file('app.json', generateMultiScreenAppJson(multiOpts))
      zip.file('package.json', generateMultiScreenPackageJson(multiOpts))
      zip.file('tsconfig.json', generateTsConfig())
      zip.file('babel.config.js', generateBabelConfig())
      zip.file('.gitignore', generateGitignore())
      zip.file('README.md', generateMultiScreenReadme(multiOpts))

      const zipBlob = await zip.generateAsync({ type: 'blob' })
      triggerDownload(zipBlob, `${brandedName(projectName)}_Expo.zip`)
      onToast(`Expo project exported (${allScreens.length} screens)!`)
      trackEvent('project_exported', { format: 'expo_multi', screen_count: allScreens.length })
    } catch (err) {
      onToast(`Export failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [onToast, downloadExpoProject])

  return { downloadPNG, downloadTSX, downloadZIP, downloadExpoProject, downloadExpoMultiScreen }
}
