import { useCallback } from 'react'
import JSZip from 'jszip'
import { captureScreenAtFullRes } from '../utils/screenCapture'
import { convertTreeToTSX } from '../utils/exportTsx'
import { getDevicePreset } from '../constants/devices'
import { trackEvent } from '../lib/analytics'
import type { ComponentNode } from '../types/mokkoi'

export interface ExportTarget {
  screenId: string
  screenName: string
  tree: ComponentNode
  deviceId: string
  originalPrompt?: string
}

interface UseScreenExportOpts {
  phoneFrameRefs: React.RefObject<Map<string, HTMLDivElement>>
  onToast: (msg: string) => void
}

/** PascalCase name for TSX component filenames (e.g. "Create a fitness app" → "CreateAFitnessApp") */
function safeName(name: string): string {
  return (name || 'Screen')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
    .slice(0, 40)
}

/** Clean filename: remove special chars, replace spaces with underscores, prefix with Mokkoi_ */
function brandedName(name: string): string {
  const clean = (name || 'Screen')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 40)
  return `Mokkoi_${clean}`
}

function generateReadme(target: ExportTarget): string {
  const device = getDevicePreset(target.deviceId)
  const name = safeName(target.screenName)
  return `# ${target.screenName}

Generated by [Mokkoi](https://mokkoi.com)

## Screen Info

- **Name:** ${target.screenName}
- **Device:** ${device.name} (${device.width}x${device.height})
${target.originalPrompt ? `- **Prompt:** ${target.originalPrompt}` : ''}

## Quick Start with Expo

\`\`\`bash
npx create-expo-app my-app --template blank-typescript
cd my-app
\`\`\`

Copy \`${name}.tsx\` into your project, then import it:

\`\`\`tsx
import ${name}Screen from './${name}';

export default function App() {
  return <${name}Screen />;
}
\`\`\`

Run:

\`\`\`bash
npx expo start
\`\`\`

## Files

| File | Description |
|------|-------------|
| \`screen.png\` | High-resolution screenshot (@2x) |
| \`${name}.tsx\` | React Native component |
| \`README.md\` | This file |
`
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function useScreenExport({ phoneFrameRefs, onToast }: UseScreenExportOpts) {
  const downloadPNG = useCallback(async (target: ExportTarget) => {
    onToast('Capturing screenshot...')
    try {
      const blob = await captureScreenAtFullRes(target.screenId, phoneFrameRefs.current!)
      triggerDownload(blob, `${brandedName(target.screenName)}.png`)
      onToast('Screenshot saved!')
      trackEvent('screen_downloaded', { format: 'png' })
    } catch (err) {
      onToast(`Screenshot failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [phoneFrameRefs, onToast])

  const downloadTSX = useCallback((target: ExportTarget) => {
    try {
      const code = convertTreeToTSX(target.tree, target.screenName)
      const blob = new Blob([code], { type: 'text/plain' })
      triggerDownload(blob, `${brandedName(target.screenName)}.tsx`)
      onToast('Code downloaded!')
      trackEvent('screen_downloaded', { format: 'tsx' })
    } catch (err) {
      onToast(`Download failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [onToast])

  const downloadZIP = useCallback(async (target: ExportTarget) => {
    onToast('Preparing package...')
    try {
      const zip = new JSZip()
      const name = safeName(target.screenName)

      // Screenshot
      const pngBlob = await captureScreenAtFullRes(target.screenId, phoneFrameRefs.current!)
      zip.file('screen.png', pngBlob)

      // Code
      zip.file(`${name}.tsx`, convertTreeToTSX(target.tree, target.screenName))

      // README
      zip.file('README.md', generateReadme(target))

      const zipBlob = await zip.generateAsync({ type: 'blob' })
      triggerDownload(zipBlob, `${brandedName(target.screenName)}.zip`)
      onToast('Package downloaded!')
      trackEvent('screen_downloaded', { format: 'zip' })
    } catch (err) {
      onToast(`Package failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
    }
  }, [phoneFrameRefs, onToast])

  return { downloadPNG, downloadTSX, downloadZIP }
}
