// Expo project scaffold generators.
// Pure template functions — no side effects, no network calls.

export interface ScaffoldOpts {
  screenName: string      // PascalCase component name (e.g. "FitnessDashboard")
  projectName: string     // Human-readable project name
  prompt?: string         // Original generation prompt
  deviceWidth: number
  deviceHeight: number
}

/** Multi-screen project scaffold options */
export interface MultiScreenOpts {
  projectName: string
  screens: { name: string; prompt?: string; tabLabels?: string[] }[]  // PascalCase names
  /** Screens that share tab bars → grouped into a BottomTabNavigator */
  tabGroup?: { screenNames: string[]; labels: string[] }
}

function toSlug(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 40) || 'mokkoi-app'
}

/** Clean display name: strip quotes, special chars, truncation artifacts */
function cleanDisplayName(name: string, fallback: string): string {
  const cleaned = name
    .replace(/^["']|["']$/g, '')  // strip leading/trailing quotes
    .replace(/\.\.\.$/, '')       // strip trailing ellipsis
    .trim()
  return cleaned.length > 3 ? cleaned : fallback
}

export function generateAppTsx(opts: ScaffoldOpts): string {
  return `import { StatusBar } from 'expo-status-bar';
import ${opts.screenName}Screen from './${opts.screenName}';

export default function App() {
  return (
    <>
      <${opts.screenName}Screen />
      <StatusBar style="light" />
    </>
  );
}
`
}

export function generateAppJson(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  const slug = toSlug(displayName)
  return JSON.stringify({
    expo: {
      name: displayName,
      slug,
      version: '1.0.0',
      orientation: 'portrait',
      userInterfaceStyle: 'dark',
      ios: { supportsTablet: false },
      android: { adaptiveIcon: { backgroundColor: '#0A0A1A' } },
      web: { bundler: 'metro' },
    },
  }, null, 2) + '\n'
}

export function generatePackageJson(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  const slug = toSlug(displayName)
  return JSON.stringify({
    name: slug,
    version: '1.0.0',
    main: 'expo/AppEntry.js',
    scripts: {
      start: 'expo start',
      android: 'expo start --android',
      ios: 'expo start --ios',
    },
    dependencies: {
      'expo': '~55.0.0',
      'expo-status-bar': '~3.0.9',
      'react': '19.2.0',
      'react-native': '0.83.0',
    },
    devDependencies: {
      '@babel/core': '^7.25.0',
      'typescript': '~5.8.0',
    },
    private: true,
  }, null, 2) + '\n'
}

export function generateTsConfig(): string {
  return JSON.stringify({
    extends: 'expo/tsconfig.base',
    compilerOptions: {
      strict: true,
    },
  }, null, 2) + '\n'
}

export function generateBabelConfig(): string {
  return `module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`
}

export function generateGitignore(): string {
  return `node_modules/
.expo/
dist/
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/
`
}

export function generateReadme(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  return `# ${displayName}

Generated by [Mokkoi](https://mokkoi.com) — AI Mobile App Builder

## Screen

- **Component:** ${opts.screenName}Screen
- **Device:** ${opts.deviceWidth}x${opts.deviceHeight}
${opts.prompt ? `- **Prompt:** ${opts.prompt}` : ''}

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

Scan the QR code with **Expo Go** (iOS/Android) to preview on your phone.

## Adding More Packages

\`\`\`bash
npx expo install expo-camera expo-location
\`\`\`

## Build for Production

\`\`\`bash
npx eas build --platform all
\`\`\`

See [Expo docs](https://docs.expo.dev) for more.
`
}

// ── Multi-screen project generators ──────────────────────────────

export function generateMultiScreenAppTsx(opts: MultiScreenOpts): string {
  const imports = opts.screens
    .map(s => `import ${s.name}Screen from './screens/${s.name}';`)
    .join('\n')

  const firstScreen = opts.screens[0]?.name || 'Home'
  const tabGroup = opts.tabGroup

  // If we have a tab group, split screens into tab vs stack
  if (tabGroup && tabGroup.screenNames.length >= 2) {
    const tabScreenNames = new Set(tabGroup.screenNames)
    const stackScreens = opts.screens.filter(s => !tabScreenNames.has(s.name))

    const tabScreenEntries = opts.screens
      .filter(s => tabScreenNames.has(s.name))
      .map((s, i) => {
        const label = tabGroup.labels[i] || s.name
        return `          <Tab.Screen name="${s.name}" component={${s.name}Screen} options={{ tabBarLabel: '${label}' }} />`
      })
      .join('\n')

    const stackEntries = stackScreens
      .map(s => `          <Stack.Screen name="${s.name}" component={${s.name}Screen} />`)
      .join('\n')

    const hasStackScreens = stackScreens.length > 0

    return `import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
${hasStackScreens ? "import { createNativeStackNavigator } from '@react-navigation/native-stack';\n" : ''}${imports}

const Tab = createBottomTabNavigator();
${hasStackScreens ? 'const Stack = createNativeStackNavigator();\n' : ''}
function TabScreens() {
  return (
    <Tab.Navigator
      screenOptions={{
        headerShown: false,
        tabBarStyle: { backgroundColor: '#1A1A1A', borderTopColor: 'rgba(255,255,255,0.08)' },
        tabBarActiveTintColor: '#818CF8',
        tabBarInactiveTintColor: '#64748b',
      }}
    >
${tabScreenEntries}
    </Tab.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
${hasStackScreens ? `      <Stack.Navigator screenOptions={{ headerShown: false, contentStyle: { backgroundColor: '#0A0A1A' }, animation: 'slide_from_right' }}>
        <Stack.Screen name="Tabs" component={TabScreens} />
${stackEntries}
      </Stack.Navigator>` : '      <TabScreens />'}
      <StatusBar style="light" />
    </NavigationContainer>
  );
}
`
  }

  // Default: all stack screens
  const stackScreens = opts.screens
    .map(s => `        <Stack.Screen name="${s.name}" component={${s.name}Screen} />`)
    .join('\n')

  return `import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
${imports}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator
        initialRouteName="${firstScreen}"
        screenOptions={{
          headerShown: false,
          contentStyle: { backgroundColor: '#0A0A1A' },
          animation: 'slide_from_right',
        }}
      >
${stackScreens}
      </Stack.Navigator>
      <StatusBar style="light" />
    </NavigationContainer>
  );
}
`
}

export function generateMultiScreenPackageJson(opts: MultiScreenOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screens[0]?.name || 'App')
  const slug = toSlug(displayName)
  const deps: Record<string, string> = {
    'expo': '~55.0.0',
    'expo-status-bar': '~3.0.9',
    'react': '19.2.0',
    'react-native': '0.83.0',
    '@react-navigation/native': '^7.1.6',
    '@react-navigation/native-stack': '^7.3.10',
    'react-native-screens': '~4.10.0',
    'react-native-safe-area-context': '~5.4.0',
  }
  if (opts.tabGroup) {
    deps['@react-navigation/bottom-tabs'] = '^7.3.10'
  }
  return JSON.stringify({
    name: slug,
    version: '1.0.0',
    main: 'expo/AppEntry.js',
    scripts: {
      start: 'expo start',
      android: 'expo start --android',
      ios: 'expo start --ios',
    },
    dependencies: deps,
    devDependencies: {
      '@babel/core': '^7.25.0',
      'typescript': '~5.8.0',
    },
    private: true,
  }, null, 2) + '\n'
}

export function generateMultiScreenAppJson(opts: MultiScreenOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screens[0]?.name || 'App')
  const slug = toSlug(displayName)
  return JSON.stringify({
    expo: {
      name: displayName,
      slug,
      version: '1.0.0',
      orientation: 'portrait',
      userInterfaceStyle: 'dark',
      ios: { supportsTablet: false },
      android: { adaptiveIcon: { backgroundColor: '#0A0A1A' } },
      web: { bundler: 'metro' },
    },
  }, null, 2) + '\n'
}

export function generateMultiScreenReadme(opts: MultiScreenOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screens[0]?.name || 'App')
  const screenList = opts.screens
    .map(s => `| \`${s.name}Screen\` | screens/${s.name}.tsx | ${s.prompt || '-'} |`)
    .join('\n')

  return `# ${displayName}

Generated by [Mokkoi](https://mokkoi.com) — AI Mobile App Builder

## Screens (${opts.screens.length})

| Component | File | Prompt |
|-----------|------|--------|
${screenList}

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

Scan the QR code with **Expo Go** (iOS/Android) to preview on your phone.

## Navigation

This app uses **React Navigation** with a native stack navigator.
All screens are wired in \`App.tsx\`. To navigate between screens:

\`\`\`tsx
import { useNavigation } from '@react-navigation/native';

function MyScreen() {
  const navigation = useNavigation();
  return (
    <Button onPress={() => navigation.navigate('${opts.screens[1]?.name || 'OtherScreen'}')} />
  );
}
\`\`\`

## Build for Production

\`\`\`bash
npx eas build --platform all
\`\`\`

See [Expo docs](https://docs.expo.dev) for more.
`
}
