// Expo project scaffold generators.
// Pure template functions — no side effects, no network calls.

export interface ScaffoldOpts {
  screenName: string      // PascalCase component name (e.g. "FitnessDashboard")
  projectName: string     // Human-readable project name
  prompt?: string         // Original generation prompt
  deviceWidth: number
  deviceHeight: number
}

function toSlug(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 40) || 'mokkoi-app'
}

/** Clean display name: strip quotes, special chars, truncation artifacts */
function cleanDisplayName(name: string, fallback: string): string {
  const cleaned = name
    .replace(/^["']|["']$/g, '')  // strip leading/trailing quotes
    .replace(/\.\.\.$/, '')       // strip trailing ellipsis
    .trim()
  return cleaned.length > 3 ? cleaned : fallback
}

export function generateAppTsx(opts: ScaffoldOpts): string {
  return `import { StatusBar } from 'expo-status-bar';
import ${opts.screenName}Screen from './${opts.screenName}';

export default function App() {
  return (
    <>
      <${opts.screenName}Screen />
      <StatusBar style="light" />
    </>
  );
}
`
}

export function generateAppJson(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  const slug = toSlug(displayName)
  return JSON.stringify({
    expo: {
      name: displayName,
      slug,
      version: '1.0.0',
      orientation: 'portrait',
      userInterfaceStyle: 'dark',
      ios: { supportsTablet: false },
      android: { adaptiveIcon: { backgroundColor: '#0A0A1A' } },
      web: { bundler: 'metro' },
    },
  }, null, 2) + '\n'
}

export function generatePackageJson(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  const slug = toSlug(displayName)
  return JSON.stringify({
    name: slug,
    version: '1.0.0',
    main: 'expo/AppEntry.js',
    scripts: {
      start: 'expo start',
      android: 'expo start --android',
      ios: 'expo start --ios',
    },
    dependencies: {
      'expo': '~55.0.0',
      'expo-status-bar': '~3.0.9',
      'react': '19.2.0',
      'react-native': '0.83.0',
    },
    devDependencies: {
      '@babel/core': '^7.25.0',
      'typescript': '~5.8.0',
    },
    private: true,
  }, null, 2) + '\n'
}

export function generateTsConfig(): string {
  return JSON.stringify({
    extends: 'expo/tsconfig.base',
    compilerOptions: {
      strict: true,
    },
  }, null, 2) + '\n'
}

export function generateBabelConfig(): string {
  return `module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`
}

export function generateGitignore(): string {
  return `node_modules/
.expo/
dist/
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/
`
}

export function generateReadme(opts: ScaffoldOpts): string {
  const displayName = cleanDisplayName(opts.projectName, opts.screenName)
  return `# ${displayName}

Generated by [Mokkoi](https://mokkoi.com) — AI Mobile App Builder

## Screen

- **Component:** ${opts.screenName}Screen
- **Device:** ${opts.deviceWidth}x${opts.deviceHeight}
${opts.prompt ? `- **Prompt:** ${opts.prompt}` : ''}

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

Scan the QR code with **Expo Go** (iOS/Android) to preview on your phone.

## Adding More Packages

\`\`\`bash
npx expo install expo-camera expo-location
\`\`\`

## Build for Production

\`\`\`bash
npx eas build --platform all
\`\`\`

See [Expo docs](https://docs.expo.dev) for more.
`
}
