import {
  componentTreeToTSX,
  writeScreenFile,
} from '../utils/file-writer.js';
import { getScreensByProject } from '../utils/supabase-client.js';

export const exportProjectTool = {
  name: 'export_project',
  description:
    'Export the current Mokkoi project as a runnable Expo app. Fetches all screens from the canvas, generates React Native .tsx files with React Navigation, and writes a complete project scaffold to disk. Requires MOKKOI_PROJECT_ID to be set.',
  inputSchema: {
    type: 'object' as const,
    properties: {
      outputDir: {
        type: 'string',
        description: 'Output directory for the Expo project (default: ./mokkoi-expo-app)',
      },
      screenNames: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional list of screen names to include. If omitted, exports all screens.',
      },
    },
    required: [],
  },
};

function toPascalCase(name: string): string {
  return (name || 'Screen')
    .replace(/^(create|make|design|build|generate|regenerate)\s+(a|an|the|my|this)\s+/i, '')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(w => w.length > 0)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
    .slice(0, 40) || 'Screen';
}

function toSlug(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 40) || 'mokkoi-app';
}

function generateAppTsx(screens: { name: string }[]): string {
  const imports = screens
    .map(s => `import ${s.name}Screen from './screens/${s.name}';`)
    .join('\n');

  const firstScreen = screens[0]?.name || 'Home';
  const stackScreens = screens
    .map(s => `        <Stack.Screen name="${s.name}" component={${s.name}Screen} />`)
    .join('\n');

  return `import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
${imports}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator
        initialRouteName="${firstScreen}"
        screenOptions={{
          headerShown: false,
          contentStyle: { backgroundColor: '#0A0A1A' },
          animation: 'slide_from_right',
        }}
      >
${stackScreens}
      </Stack.Navigator>
      <StatusBar style="light" />
    </NavigationContainer>
  );
}
`;
}

function generatePackageJson(projectName: string, hasMultipleScreens: boolean): string {
  const slug = toSlug(projectName);
  const deps: Record<string, string> = {
    'expo': '~55.0.0',
    'expo-status-bar': '~3.0.9',
    'react': '19.2.0',
    'react-native': '0.83.0',
  };
  if (hasMultipleScreens) {
    deps['@react-navigation/native'] = '^7.1.6';
    deps['@react-navigation/native-stack'] = '^7.3.10';
    deps['react-native-screens'] = '~4.10.0';
    deps['react-native-safe-area-context'] = '~5.4.0';
  }
  return JSON.stringify({
    name: slug,
    version: '1.0.0',
    main: 'expo/AppEntry.js',
    scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios' },
    dependencies: deps,
    devDependencies: { '@babel/core': '^7.25.0', 'typescript': '~5.8.0' },
    private: true,
  }, null, 2) + '\n';
}

function generateAppJson(projectName: string): string {
  const slug = toSlug(projectName);
  return JSON.stringify({
    expo: {
      name: projectName,
      slug,
      version: '1.0.0',
      orientation: 'portrait',
      userInterfaceStyle: 'dark',
      ios: { supportsTablet: false },
      android: { adaptiveIcon: { backgroundColor: '#0A0A1A' } },
      web: { bundler: 'metro' },
    },
  }, null, 2) + '\n';
}

function generateReadme(projectName: string, screens: { name: string }[]): string {
  const screenList = screens.map(s => `| \`${s.name}Screen\` | screens/${s.name}.tsx |`).join('\n');
  return `# ${projectName}

Generated by [Mokkoi](https://mokkoi.com) — AI Mobile App Builder

## Screens (${screens.length})

| Component | File |
|-----------|------|
${screenList}

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

Scan the QR code with **Expo Go** (iOS/Android) to preview on your phone.

## Build for Production

\`\`\`bash
npx eas build --platform all
\`\`\`

See [Expo docs](https://docs.expo.dev) for more.
`;
}

export async function handleExportProject(args: {
  outputDir?: string;
  screenNames?: string[];
}): Promise<{ content: Array<{ type: 'text'; text: string }> }> {
  try {
    // Fetch all screens from the project
    let allScreens = await getScreensByProject();

    if (allScreens.length === 0) {
      return {
        content: [{
          type: 'text' as const,
          text: JSON.stringify({
            success: false,
            error: 'No screens found. Make sure MOKKOI_PROJECT_ID and MOKKOI_SUPABASE_URL/MOKKOI_SUPABASE_ANON_KEY are set.',
          }),
        }],
      };
    }

    // Filter by screen names if specified
    if (args.screenNames && args.screenNames.length > 0) {
      const nameSet = new Set(args.screenNames.map(n => n.toLowerCase()));
      allScreens = allScreens.filter(s => nameSet.has(s.name.toLowerCase()));
    }

    const outputDir = args.outputDir || 'mokkoi-expo-app';
    const projectName = process.env.MOKKOI_PROJECT_NAME || 'Mokkoi App';
    const hasMultipleScreens = allScreens.length > 1;

    // Deduplicate PascalCase names
    const usedNames = new Set<string>();
    const screenMeta: { name: string; originalName: string }[] = [];

    for (const screen of allScreens) {
      let name = toPascalCase(screen.name);
      if (usedNames.has(name)) {
        let i = 2;
        while (usedNames.has(`${name}${i}`)) i++;
        name = `${name}${i}`;
      }
      usedNames.add(name);
      screenMeta.push({ name, originalName: screen.name });
    }

    const writtenFiles: string[] = [];

    // Write screen TSX files
    for (let i = 0; i < allScreens.length; i++) {
      const screen = allScreens[i];
      const meta = screenMeta[i];
      const tsx = componentTreeToTSX(screen.component_tree, meta.name);
      const filePath = hasMultipleScreens
        ? `${outputDir}/screens/${meta.name}.tsx`
        : `${outputDir}/${meta.name}.tsx`;
      await writeScreenFile(filePath, tsx);
      writtenFiles.push(filePath);
    }

    // Write App.tsx
    if (hasMultipleScreens) {
      await writeScreenFile(`${outputDir}/App.tsx`, generateAppTsx(screenMeta));
    } else {
      const name = screenMeta[0].name;
      const appContent = `import { StatusBar } from 'expo-status-bar';
import ${name}Screen from './${name}';

export default function App() {
  return (
    <>
      <${name}Screen />
      <StatusBar style="light" />
    </>
  );
}
`;
      await writeScreenFile(`${outputDir}/App.tsx`, appContent);
    }
    writtenFiles.push(`${outputDir}/App.tsx`);

    // Write scaffold files
    await writeScreenFile(`${outputDir}/package.json`, generatePackageJson(projectName, hasMultipleScreens));
    await writeScreenFile(`${outputDir}/app.json`, generateAppJson(projectName));
    await writeScreenFile(`${outputDir}/tsconfig.json`, JSON.stringify({ extends: 'expo/tsconfig.base', compilerOptions: { strict: true } }, null, 2) + '\n');
    await writeScreenFile(`${outputDir}/babel.config.js`, `module.exports = function (api) {\n  api.cache(true);\n  return { presets: ['babel-preset-expo'] };\n};\n`);
    await writeScreenFile(`${outputDir}/.gitignore`, 'node_modules/\n.expo/\ndist/\nweb-build/\n');
    await writeScreenFile(`${outputDir}/README.md`, generateReadme(projectName, screenMeta));

    writtenFiles.push(
      `${outputDir}/package.json`,
      `${outputDir}/app.json`,
      `${outputDir}/tsconfig.json`,
      `${outputDir}/babel.config.js`,
      `${outputDir}/README.md`,
    );

    return {
      content: [{
        type: 'text' as const,
        text: JSON.stringify({
          success: true,
          outputDir,
          totalScreens: allScreens.length,
          files: writtenFiles,
          hasNavigation: hasMultipleScreens,
          message: `Expo project exported to ${outputDir}/ with ${allScreens.length} screen${allScreens.length > 1 ? 's' : ''}. Run: cd ${outputDir} && npm install && npx expo start`,
        }, null, 2),
      }],
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      content: [{
        type: 'text' as const,
        text: JSON.stringify({ success: false, error: message }),
      }],
    };
  }
}
